package com.cprassist.ui.viewmodel

import android.app.Application
import android.content.Intent
import androidx.core.content.FileProvider
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.cprassist.data.database.SessionDatabase
import com.cprassist.data.database.SessionEntity
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.launch
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * ViewModel for Session History screen
 */
class SessionHistoryViewModel(application: Application) : AndroidViewModel(application) {

    private val context = application.applicationContext
    private val database = SessionDatabase.getInstance(context)
    private val sessionDao = database.sessionDao()

    val sessions: Flow<List<SessionEntity>> = sessionDao.getAllSessions()

    /**
     * Delete a specific session
     */
    fun deleteSession(session: SessionEntity) {
        viewModelScope.launch {
            sessionDao.deleteSession(session)
        }
    }

    /**
     * Delete all sessions
     */
    fun deleteAllSessions() {
        viewModelScope.launch {
            sessionDao.deleteAllSessions()
        }
    }

    /**
     * Export a session to a file and trigger share
     */
    fun exportSession(session: SessionEntity) {
        viewModelScope.launch {
            val sessionWithEvents = sessionDao.getSessionWithEvents(session.id)
            if (sessionWithEvents != null) {
                val content = generateExportContent(sessionWithEvents.session, sessionWithEvents.events.size)
                shareContent(content, session.id)
            }
        }
    }

    private fun generateExportContent(session: SessionEntity, eventCount: Int): String {
        val sb = StringBuilder()
        sb.appendLine("═══════════════════════════════════════════")
        sb.appendLine("         CPR ASSIST SESSION EXPORT          ")
        sb.appendLine("═══════════════════════════════════════════")
        sb.appendLine()
        sb.appendLine("Session ID: ${session.id}")
        sb.appendLine("Date: ${session.formatStartTime()}")
        sb.appendLine("Duration: ${session.formatDuration()}")
        sb.appendLine("Outcome: ${session.getOutcome()}")
        sb.appendLine()
        sb.appendLine("───────────────────────────────────────────")
        sb.appendLine("                 STATISTICS                 ")
        sb.appendLine("───────────────────────────────────────────")
        sb.appendLine("Total Events: ${session.eventCount}")
        sb.appendLine("Shocks: ${session.shockCount}")
        sb.appendLine("Adrenaline: ${session.adrenalineCount}")
        sb.appendLine("Amiodarone: ${session.amiodaroneCount}")
        if (session.arrestCount > 1) {
            sb.appendLine("Re-arrests: ${session.arrestCount - 1}")
        }
        sb.appendLine()
        sb.appendLine("───────────────────────────────────────────")
        sb.appendLine()
        sb.appendLine(session.summaryText)
        sb.appendLine()
        sb.appendLine("═══════════════════════════════════════════")
        sb.appendLine("Generated by CPR Assist")

        return sb.toString()
    }

    private fun shareContent(content: String, sessionId: String) {
        val timestamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.US).format(Date())
        val fileName = "cpr_session_${timestamp}.txt"

        val file = File(context.cacheDir, fileName)
        file.writeText(content)

        val uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            file
        )

        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_SUBJECT, "CPR Assist Session Export")
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }

        context.startActivity(Intent.createChooser(intent, "Share Session").apply {
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        })
    }
}
